# This is a basic workflow to help you get started with Actions

name: Matrix

# Controls when the workflow will run
on: [workflow_dispatch, push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    concurrency:
     group: grupa
     #cancel-in-progress: true
     
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
       os: [ubuntu-latest, windows-latest]
       images: [hello-world, alpine]
       exclude:
         - images: alpine
           os: windows-latest
       include:
          - images: amd64/alpine
            os: ubuntu-20.04 
       
    runs-on: ${{matrix.os}}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Docker details
        run: docker info

      # Runs a single command using the runners shell
      - name: Run iamge on ${{matrix.os}}
        run: docker run ${{matrix.images}}

 
        
