# This is a basic workflow to help you get started with Actions

name: Matrix

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    strategy:
      matrix:
       os: [ubuntu-latest, windows-latest]
       images: [hello-world, alpine]
    runs-on: ${{matrix.os}}
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Docker details
        run: docker info

      # Runs a single command using the runners shell
      - name: Run iamge on ${{matrix.os}}
        run: docker run ${{matrix.images}}

 
        
